<?php

namespace AppBundle\Repository;

/**
 * CguRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CguRepository extends \Doctrine\ORM\EntityRepository
{
}
