<?php

namespace AppBundle\Repository;

/**
 * CompetenceGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
