<?php

namespace AppBundle\Repository;

/**
 * CompetenceLangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceLangueRepository extends \Doctrine\ORM\EntityRepository
{
}
