<?php

namespace AppBundle\Repository;

/**
 * CulteWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CulteWordRepository extends \Doctrine\ORM\EntityRepository
{
}
