<?php

namespace AppBundle\Repository;

/**
 * InformationMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationMeRepository extends \Doctrine\ORM\EntityRepository
{
}
