<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Query-builder Login
     * @return array
     */
    public function authorizedAccess($email, $password) {
        return $this->createQueryBuilder("u")
            ->leftJoin("u.role", "r")
            ->addSelect("u", "r")
            ->andWhere("u.email = :email")
            ->andWhere("u.password = :password")
            ->setParameter("email", $email)
            ->setParameter("password", $password)
            ->getQuery()
            ->execute();
    }

}
